### ISSUE TITLE
Bug in Base58

### ISSUE THREAD

**Issue by mitja-bochmann** [phantasma-io/PhantasmaChain#1]
To determine the leading zeroes, input should be compared to 0 and not to Alphabet[0] (= 1)

`for (int i = 0; i < input.Length && input[i] == Alphabet[0]; i++) 
{
                leadingZeros++;
            }`

**Comment by Relfos** [comment]
Valid strings in Base58 can not contain zeros. If they do, a exception will be triggered [here](https://github.com/phantasma-io/PhantasmaChain/blob/master/PhantasmaChain/Cryptography/Base58.cs#L19).

"Compared to Base64, the following similar-looking letters are omitted: 0 (zero), O (capital o), I (capital i) and l (lower case L) as well as the non-alphanumeric characters + (plus) and / (slash)." [Link](https://en.wikipedia.org/wiki/Base58)
