### ISSUE TITLE
System.Random is not cryptographically safe to use!

### ISSUE THREAD

**Issue by Coding-Enthusiast** [phantasma-io/PhantasmaChain#10]
`System.Random` must be avoided anywhere that requires a secure random number generator, this class is not designed for that purpose. If you don't want to deal with RNGs at this point then at least use `System.Security.Cryptography.RNGCryptoServiceProvider` instead.  
You also should try to avoid using RNGs altogether in places such as [this](https://github.com/phantasma-io/PhantasmaChain/blob/6cfbea011ac01d0979b56087f50ce9a454c57494/Phantasma.Cryptography/ECDsa/ECDsa.cs#L43), instead use deterministic methods such as [RFC6979](https://tools.ietf.org/html/rfc6979).

**Comment by Relfos** [comment]
Thanks for your message, we are aware of it, it is on our internal TODO list, I'll do a commit soon to use the RNGCryptoServiceProvider
