### ISSUE TITLE
Possible MIN/MAX mixup?

### ISSUE THREAD

**Issue by rbisset82** [phantasma-io/PhantasmaChain#4]
PhantasmaChain/Phantasma.Blockchain/Contracts/Native/MessagingContract.cs

This may be nothing, and my coding isn't great,  but min and max value look wrong.

public const int MIN_MESSAGE_LENGTH = 1024 * 64;
public const int MAX_MESSAGE_LENGTH = 16;

and

Runtime.Expect(content.Length >= MIN_MESSAGE_LENGTH, "message too small");
Runtime.Expect(content.Length <= MAX_MESSAGE_LENGTH, "message too large");

Like I said my coding is crap but I noticed this when looking around yesterday and thought it was worth pointing out.

**Comment by Relfos** [comment]
Seems you're right, I'm going to fix that!
